const main  = async () =>{
    console.log("hello world");
}

main().catch(err=>{
    console.log("Error : ",err);
})